Lg 4 task creation
savoirfairelinux/project-addons pull request #103
Opened 2018-10-10 19:42 UTC by eilst

2018-10-11 16:26 UTC, rimbendhaou requested changes

2018-10-11 16:26 UTC, rimbendhaou commented on project_event/models/project_task.py
>              if vals['activity_task_type'] == 'activity':
@eilst else? if activity_task_type not in val? there is no return_create !

2018-10-11 16:26 UTC, rimbendhaou commented on project_event/models/project_task.py
> +                vals['message_follower_ids'] = None
@eilst the is an error when we create event,activity,task from template(with wizard).
ERROR: duplicate key value violates unique constraint "mail_followers_mail_followers_res_partner_res_model_id_uniq"

2018-10-11 16:26 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    def create_main_task(self, vals):
@eilst there is already a main task created from template, main task is duplicated in this case

2018-10-11 16:28 UTC, eilst commented on project_event/models/project_task.py
> +    def create_main_task(self, vals):
But what about if there is no template

2018-10-11 16:36 UTC, eilst commented on project_event/models/project_task.py
>              if vals['activity_task_type'] == 'activity':
Well, it is always there because it is either a task or an activity, it cannot be something else. isn't?

2018-10-11 19:19 UTC, eilst commented on project_event/models/project_task.py
> +    def create_main_task(self, vals):
Done

2018-10-11 19:20 UTC, eilst commented on project_event/models/project_task.py
>              if vals['activity_task_type'] == 'activity':
Done

2018-10-11 22:23 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    def create_main_task(self, vals):
@eilst we have to check if we are creating from template or not

2018-10-11 22:25 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    def create_main_task(self, vals):
@eilst we have to check if we are creating from template or no

2018-10-12 20:16 UTC, rimbendhaou commented on project_event/models/project_task.py
> +                vals['message_follower_ids'] = None
@eilst this prob was not resolved

2018-10-12 20:36 UTC, eilst commented on project_event/models/project_task.py
> +    def create_main_task(self, vals):
done

2018-10-12 20:41 UTC, eilst commented on project_event/models/project_task.py
> +                vals['message_follower_ids'] = None
Done

2018-10-12 20:57 UTC, rimbendhaou approved these changes
looks ok

2018-10-12 20:57 UTC, merged