[ADD] French translations
savoirfairelinux/project-addons pull request #104
Opened 2018-10-10 20:56 UTC by eilst

2018-10-10 21:04 UTC, rimbendhaou requested changes
@eilst some missing translation

2018-10-10 21:04 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +""Last-Translator: <:uis GARCIA RUIZ luis,garcia@savoirfairelinux.com>\n"
@eilst why "" double, and for the translator name <:uis it looks incorrect

2018-10-10 21:04 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Task Client"
@eilst Client de la tâch

2018-10-10 21:04 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Task Responsible"
@eilst Responsable de la tâche

2018-10-10 21:04 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Reservation event"
@eilst translation

2018-10-10 21:04 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Project Task Search"
not translated

2018-10-10 21:04 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Project Activity Search"
@eilst not transalated

2018-10-12 16:13 UTC, eilst commented on project_event/i18n/fr.po
> +msgstr "Project Task Search"
Done

2018-10-12 16:13 UTC, eilst commented on project_event/i18n/fr.po
> +msgstr "Project Activity Search"
Done

2018-10-12 18:37 UTC, rimbendhaou approved these changes
looks ok

2018-10-12 18:41 UTC, rimbendhaou approved these changes

2018-10-12 18:41 UTC, merged