Jr add auditlog activity and task form
savoirfairelinux/project-addons pull request #110
Opened 2018-10-12 15:54 UTC by jananjoy

Tâche #231 Adding Audit log for the Activity and Task form 
- Changes the project task model and views for  Audit log in Activity and Task Form
- Remove overriding of the  write method
- Do the language translation for the Project event module [related with Audit log functionalities]

2018-10-15 19:54 UTC, rimbendhaou requested changes

2018-10-15 19:54 UTC, rimbendhaou commented on project_event/data/auditlog_rule.xml
> +        <field name="name">project Task Logs</field>
Project Task Logs

2018-10-15 19:54 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgid "Activty Logs"
Activity Logs

2018-10-15 19:54 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    activty_log_count = fields.Integer(
@jananjoy we need only one field to count logs

2018-10-15 19:54 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    def _compute_activty_log_count(self):
@jananjoy why you define same method twice?

2018-10-15 19:54 UTC, rimbendhaou commented on project_event/views/auditlog_log.xml
> +        <record model="ir.actions.act_window" id="action_activity_to_auditlog_log">
@jananjoy we can use only one act_window for task logs and activity logs

2018-10-15 22:13 UTC, rimbendhaou approved these changes

2018-10-15 22:13 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +
@jananjoy delete the following lines

2018-10-15 22:14 UTC, rimbendhaou commented
@jananjoy you have to resolve conflicts

2018-10-16 15:23 UTC, rimbendhaou requested changes

2018-10-16 15:23 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "État de tâche"
@jananjoy Statut

2018-10-16 15:23 UTC, rimbendhaou commented on project_event/data/auditlog_rule.xml
> +    <record id="auditlog_project_task_rule" model="auditlog.rule">
@jananjoy you shouldent delete the auditlog.rule of the project_project model

2018-10-16 15:23 UTC, rimbendhaou commented on project_event/views/auditlog_log.xml
> +        <record model="ir.actions.act_window" id="action_project_task_auditlog_log">
you should not delete the act_window of the project_project model

2018-10-16 19:51 UTC, rimbendhaou requested changes

2018-10-16 19:51 UTC, rimbendhaou commented on project_event/models/project_task.py
> +
@jananjoy empty line

2018-10-16 19:51 UTC, rimbendhaou commented on project_event/views/auditlog_log.xml
> +          <record model="ir.actions.act_window" id="action_project_event_to_auditlog_log">
@jananjoy indentation

2018-10-16 20:09 UTC, jananjoy commented on project_event/views/auditlog_log.xml
> +          <record model="ir.actions.act_window" id="action_project_event_to_auditlog_log">
@rimbendhaou  :+1:  Done

2018-10-16 20:10 UTC, jananjoy commented on project_event/models/project_task.py
> +
@rimbendhaou :+1:  Done empty line deleted

2018-10-16 20:45 UTC, rimbendhaou approved these changes
looks ok

2018-10-16 20:45 UTC, merged