[ADD] Colors from lgharib
savoirfairelinux/project-addons pull request #148
Opened 2018-11-01 16:11 UTC by eilst

2018-11-01 21:09 UTC, rimbendhaou requested changes

2018-11-01 21:09 UTC, rimbendhaou commented on project_event/views/project_task_view.xml
> +    <record id="calendar_color_project_task_color_view" model="ir.ui.view">
@eilst Why you didn't put this code in the same view : project_event_task_calendar

2018-11-01 21:10 UTC, rimbendhaou requested changes

2018-11-01 21:10 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        default=lambda self: self.env.ref('project_event.task_category_uncategorized').id,
where is this external id: project_event.task_category_uncategorized?

2018-11-01 23:00 UTC, rimbendhaou requested changes

2018-11-01 23:00 UTC, rimbendhaou commented on project_event/views/project_task_view.xml
> +                       js_class = "calendar_colour"
@eilst indentation, no space before and after  =

2018-11-01 23:00 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        default=lambda self: self.env.ref('project_event.default_category').id,
self.env.ref('task_category_uncategorized').id,

2018-11-01 23:00 UTC, rimbendhaou commented on project_event/views/project_task_view.xml
> +              sequence="30"/>
why this empty spaces?

2018-11-02 15:44 UTC, eilst commented on project_event/models/project_task.py
> +        default=lambda self: self.env.ref('project_event.default_category').id,
done

2018-11-02 16:11 UTC, rimbendhaou approved these changes

2018-11-02 16:11 UTC, merged