[ADD] Weekly Reports #427
savoirfairelinux/project-addons pull request #216
Opened 2018-11-22 22:37 UTC by eilst

2018-11-26 23:47 UTC, rimbendhaou requested changes
the name of the room should appear only in the top (title) not in each line (according to @wbeverly ).
Better to reduce to margin size of the report

2018-11-26 23:47 UTC, rimbendhaou commented on project_resource_calendar/views/equipment_calendar_view.xml
> +                <field name="weekday"/>
we need to display this?

2018-11-26 23:47 UTC, rimbendhaou commented on project_resource_calendar/report/calendar_event_report_view.xml
> +    <report id="project_resource_calendar_report"
project_resource_calendar_weekly_event_report

2018-11-27 16:46 UTC, eilst commented on project_resource_calendar/views/equipment_calendar_view.xml
> +                <field name="weekday"/>
Yes

2018-11-27 22:40 UTC, rimbendhaou requested changes

2018-11-27 22:40 UTC, rimbendhaou commented on project_resource_calendar/report/calendar_event_report_view.xml
> +    <report id="project_resource_calendar_report"
this is not a view better to rename the file to (calendar_event_weekly_report.xml)

2018-11-27 22:40 UTC, rimbendhaou commented on project_resource_calendar/__manifest__.py
> +        'report/calendar_event_report_view.xml',
Better to rename the file to calendar_event_weekly_report we will have also another report with this name in another PR

2018-11-29 14:26 UTC, merged