[ADD] Create the 'Client Type' in the Project Event
savoirfairelinux/project-addons pull request #222
Opened 2018-11-27 00:12 UTC by jananjoy

2018-11-29 19:17 UTC, eilst commented on project_event/models/res_partner_category.py
> +    _inherit = ['res.partner.category']
You don't need to specify the name if you are already inheriting and extending, only if you want to create a new table. It's ok, but you could remove this line

2018-11-29 22:35 UTC, rimbendhaou requested changes

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/models/res_partner_category.py
> +# -*- coding: utf-8 -*-
No need in odoo11

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/models/res_partner_category_type.py
> +# -*- coding: utf-8 -*-
no need in odoo 11

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +        <field name="name">Contact Tags Form</field>
Client Type Form

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +    <record id="category_type_form" model="ir.ui.view">
better to use this id id="res_partner_category_type_form"

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +        <field name="name">Res Partner Category Type</field>
name: Client Type

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +            <form string="Category Type">
Client Type

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +    <record id="category_type_tree" model="ir.ui.view">
res_partner_category_type_tree

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +        <field name="name">Contact Tags Tree</field>
Client Types Tree

2018-11-29 22:35 UTC, rimbendhaou commented on project_event/views/res_partner_category_type_view.xml
> +            <tree string="">
string="Client Type"

2018-11-30 00:50 UTC, rimbendhaou requested changes
need access right for the new model res.partner.category.type

2018-11-30 00:50 UTC, rimbendhaou commented on project_event/models/res_partner_category_type.py
> +# © 2018 Savoir-faire Linux
You have to add the access right for this new model

2018-11-30 15:27 UTC, jananjoy commented on project_event/models/res_partner_category_type.py
> +# © 2018 Savoir-faire Linux
@rimbendhaou Done

2018-11-30 18:36 UTC, jananjoy commented
I updated access right and change the string type too

2018-11-30 22:42 UTC, rimbendhaou approved these changes

2018-11-30 22:42 UTC, merged