[ADD] Selection of recurrency field in the calendar Event pop-up form
savoirfairelinux/project-addons pull request #290
Opened 2019-01-02 18:33 UTC by jananjoy

2019-01-03 17:02 UTC, rimbendhaou requested changes

2019-01-03 17:02 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +            self.recurrent_state = "Yes"
this string should be translated (add the _ lib)

2019-01-03 17:02 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                self.recurrence_type = str(self.interval) + " par " +\
par ?  x Time(s) per week until self.final_date
(x fois par self.rrule_type jusqu'à self.final_date)
All strings should be translated, add the _() to be translated and Add the translation

2019-01-03 17:02 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                self.recurrence_type = str(self.interval) + " par " +\
par ?  x Time(s) per week for self.count self.rrule_type --> in French (x fois par self.rrule_type pendant self.count self.rrule_type)
All strings should be translated, add the _() to be translated and Add the translation

2019-01-04 20:34 UTC, rimbendhaou requested changes

2019-01-04 20:34 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                self.recurrence_type = str(self.interval) + _(" par ") +\
Check my old comment

2019-01-08 19:06 UTC, rimbendhaou requested changes

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr "fois par"
add space before and space after

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr "pendant"
add space before and space after

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr "jusqu'à"
add space before and space after

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr ""
Cliquer pour ajouter un nouveau Rendez-vous

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr ""
Vérifier si la ressource peut être réservée plusieurs fois aux même temps.

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr ""
Étiquettes d'employé

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                                       str(self.count)
str(self.interval) + _(" Time(s) per ") +\
                                       str(self.rrule_type) +\
                                       _(" for ") +\
                                       str(self.count) + _(" Time(s)")

2019-01-08 19:06 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                                       str(self.count)
in french for is translated as pour x fois

2019-01-09 01:19 UTC, rimbendhaou requested changes

2019-01-09 01:19 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr ""
And this comment?

2019-01-09 01:19 UTC, rimbendhaou commented on project_resource_calendar/i18n/fr.po
> +msgstr "Récurrence"
Type de récurrence

2019-01-09 01:19 UTC, rimbendhaou commented on project_resource_calendar/views/equipment_calendar_view.xml
> +                <field name="recurrent_state" attrs="{'readonly': [('is_task_event','=',True)]}"/>
this two fields (recurrent_state and recurrent_type) must be always readonly, because they are calculated automatically

2019-01-09 15:32 UTC, jananjoy commented
Language transalation related  task are working on "[ADD] Langauge Translation for the calendar Event popup form field label and its values "

2019-01-09 16:27 UTC, rimbendhaou approved these changes

2019-01-09 16:27 UTC, merged