[FIX] Reference to weekday in different language than english
savoirfairelinux/project-addons pull request #332
Opened 2019-02-04 17:16 UTC by eilst

2019-02-04 22:27 UTC, rimbendhaou requested changes

2019-02-04 22:27 UTC, rimbendhaou commented on project_resource_calendar/wizard/weekly_report.py
> -                'weekday': event.weekday,
Do you still use the old weekday field? If no, you have to remove it from the model

2019-02-06 17:59 UTC, eilst commented on project_resource_calendar/wizard/weekly_report.py
> -                'weekday': event.weekday,
Right, I remove it with the now useless method _get_weekday and its references

2019-02-06 19:36 UTC, rimbendhaou approved these changes

2019-02-06 19:36 UTC, merged