[ADD] Added test for calendar event user editor manager
savoirfairelinux/project-addons pull request #335
Opened 2019-02-05 22:38 UTC by lgharib

Added test for calendar event user editor manager

2019-02-07 16:06 UTC, rimbendhaou requested changes

2019-02-07 16:06 UTC, rimbendhaou commented on project_event/tests/test_security.py
> +<<<<<<< HEAD
@lgharib unresolved conflicts

2019-02-12 19:16 UTC, eilst commented on project_event/tests/test_security.py
> +    def test_920_user_editor_can_read_calendar_event(self):
After this, you are testing for 'can' but you are waiting for an error, so testes 920 to 980 are not right

2019-02-12 19:32 UTC, closed without merging

2019-02-12 19:32 UTC, eilst commented
The spec was not write correctly and it cause you to  write the wrong tests, so we will close this and create a new PR