[ADD] Added client_type inheritance
savoirfairelinux/project-addons pull request #345
Opened 2019-02-15 22:24 UTC by lgharib

Added client_type inheritance

2019-02-18 16:42 UTC, rimbendhaou requested changes

2019-02-18 16:42 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        if self.project_id:
@lgharib this code will change the edited client_type with the client_type of the partner of the project_id

2019-02-18 23:29 UTC, lgharib commented on project_event/models/project_task.py
> +        if self.project_id:
Fixed

2019-02-19 15:40 UTC, rimbendhaou approved these changes

2019-02-19 15:40 UTC, merged