[ADD] Add french translation for project event and project resource c…
savoirfairelinux/project-addons pull request #346
Opened 2019-02-21 21:40 UTC by rimbendhaou

Add french translation for project event and project resource calendar

2019-02-21 22:39 UTC, lgharib requested changes

2019-02-21 22:39 UTC, lgharib commented on project_resource_calendar/i18n/fr.po
> +msgstr "Directeur du calendrier des ressources"
Au lieu de directeur j'utiliserais "Gestionnaire"

2019-02-21 22:39 UTC, lgharib commented on project_resource_calendar/i18n/fr.po
> +msgstr "La ressource, %s, est déjà réservée pour la période spécifiée."
"La ressource, %s, est réservée pour la période spécifiée." au de "La ressource, %s, est déjà réservée pour la période spécifiée."

2019-02-21 22:39 UTC, lgharib commented on project_resource_calendar/i18n/fr.po
> +msgstr "La salle, %s, est déjà réservée pour la période spécifiée."
"La salle, %s, est réservée pour la période spécifiée." au de "La salle, %s, est déjà réservée pour la période spécifiée."

2019-02-27 20:44 UTC, eilst approved these changes

2019-02-27 22:45 UTC, lgharib approved these changes

2019-02-28 22:45 UTC, merged