[ADD]Ajout section Temps passés des tâches
savoirfairelinux/project-addons pull request #352
Opened 2019-02-26 17:03 UTC by jananjoy

2019-03-01 20:20 UTC, rimbendhaou requested changes

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/views/project_task_view.xml
> +                                    <field name="child_ids">
we dont need a page if we already have a page named technical sheet. Display the name of the section Time spent.

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        default=None,
by default it should be the same date as date_start

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        default=None,
by default it should be the same date as date_start

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        string='Actual End Time',
by default it should be the same date as date_end

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        track_visibility='onchange',
no need to add check visibility, no index or copy

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        index=True,
no need for index or copy

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        time_diff = relativedelta(fields.Datetime.from_string(self.real_date_end),
what if theses two fields are not mentioned

2019-03-01 20:20 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        time_diff = relativedelta(fields.Datetime.from_string(self.real_date_end),
you should add a test for this new functionality

2019-03-04 23:35 UTC, rimbendhaou requested changes

2019-03-04 23:35 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        default=None,
@jananjoy what about default? by default it should be the same date as date_start

2019-03-04 23:35 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        default=None,
by default it should be the same date as date_end

2019-03-04 23:35 UTC, rimbendhaou commented on project_event/tests/common.py
> +            'total_time': "1:1",
This field should be filled automatically

2019-03-04 23:35 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        self.assertEqual(diff, "0:0")
better to test with a time difference>0

2019-03-04 23:35 UTC, rimbendhaou commented on project_event/tests/common.py
> +            'real_date_end': fields.Datetime.to_string(datetime.today()),
better to have real_date_end different then real_date_start

2019-03-04 23:35 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    @api.one
You have to add also a constraint that checks if real_date_end > real_date_start

2019-03-06 20:55 UTC, eilst commented on project_event/models/project_task.py
> +        elif self.real_date_start is None:
This forces the real time fields to be filled, for now we need those fields empty by default

2019-03-07 21:07 UTC, eilst approved these changes

2019-03-07 21:07 UTC, merged