[FIX]One-time reservation printing
savoirfairelinux/project-addons pull request #367
Opened 2019-03-06 15:41 UTC by jananjoy

2019-03-06 16:33 UTC, eilst commented
Mergeor rebase 11.0, so you have the new circle-ci config

2019-03-06 23:13 UTC, rimbendhaou requested changes
Functional tests dont work. No translation for the day and month

2019-03-12 19:46 UTC, rimbendhaou approved these changes

2019-03-12 21:45 UTC, eilst approved these changes

2019-03-12 21:45 UTC, merged