[ADD] calendar employee double booking
savoirfairelinux/project-addons pull request #384
Opened 2019-03-14 14:37 UTC by rimbendhaou

2019-03-19 14:00 UTC, jananjoy requested changes

2019-03-19 14:00 UTC, jananjoy commented on project_resource_calendar/views/res_partner_view.xml
> +    <record id="view_partner_inherit_form_view_2" model="ir.ui.view">
not a good record Id  name 'view_partner_inherit_form_view_2' . Besides in the previous record id = view_employee_form_inherited and here different naming convention

2019-03-19 14:00 UTC, jananjoy commented on project_resource_calendar/__manifest__.py
> +        'views/res_partner_view.xml',
@rimbendhaou :Is dependency required or not for  res.partner  in the manifest file (reference in project event )

2019-03-19 14:00 UTC, jananjoy commented on project_resource_calendar/models/hr_employee.py
> +    )
@rimbendhaou  Add an extra line at the end as standard format

2019-03-19 14:00 UTC, jananjoy commented on project_resource_calendar/models/res.partner.py
> +    )
@rimbendhaou : Add extra line at the end of the file

2019-03-19 14:00 UTC, jananjoy commented on project_resource_calendar/views/hr_employee_view.xml
> +        <record id="view_employee_form_inherited" model="ir.ui.view">
@rimbendhaou No uniform name convention with other  files in the project . Hope need to define a standard naming conventions for the whole project

2019-03-19 14:02 UTC, jananjoy commented on project_resource_calendar/models/hr_employee.py
> +    )
@rimbendhaou Have you add the corresponding test cases to validate this variable.

2019-03-20 19:10 UTC, rimbendhaou commented on project_resource_calendar/models/hr_employee.py
> +    )
@jananjoy It is a work in progress PR (not finished yet). I still work on it.

2019-03-21 18:58 UTC, closed without merging