[FIX] Prevent the removal of a clone calendar.event
savoirfairelinux/project-addons pull request #424
Opened 2019-04-10 18:21 UTC by jananjoy

2019-04-11 18:15 UTC, rimbendhaou requested changes

2019-04-11 18:15 UTC, rimbendhaou commented on project_event/models/project_task.py
> +            if rec.task_state in \
better to check if it is not in draft

2019-04-11 18:15 UTC, rimbendhaou commented on project_event/models/project_task.py
> +                value = self.env['calendar.event'].search([
check if we have a clone or not

2019-04-11 18:15 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +        if self.event_task_id.task_state in \
why you check the state of the related project.task ?

2019-04-11 18:15 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +        if self.event_task_id.task_state in \
if it is api.multi use the for rec in self:

2019-04-11 18:15 UTC, rimbendhaou commented on project_event/models/project_task.py
> +            if rec.task_state in \
what about canceled state?

2019-04-11 18:15 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +        if self.event_task_id.task_state in \
@jananjoy keep only this unlink, we dont need the other unlink for the moment. We need to prevent the delete of the clone only

2019-04-11 18:15 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +        if self.event_task_id.task_state in \
and add the equivalent test

2019-04-11 21:00 UTC, eilst commented on project_resource_calendar/models/calendar_event.py
> +        return super(CalendarEvent, self).unlink()
inside for: 
               return super(CalendarEvent, record).unlink()

2019-04-11 21:00 UTC, eilst commented on project_resource_calendar/tests/test_calendar_event.py
> +    def test_120_unlink(self):
provide a more descriptive test name

2019-04-15 20:44 UTC, rimbendhaou requested changes

2019-04-15 20:44 UTC, rimbendhaou commented on project_resource_calendar/tests/test_calendar_event.py
> +        self.category_1 = self.Task_category.create({
there is no task_category in the common.py file or in the setup

2019-04-15 20:44 UTC, rimbendhaou commented on project_resource_calendar/tests/test_calendar_event.py
> +        self.task_1.action_option()
wizard confirmation is missing

2019-04-15 20:44 UTC, rimbendhaou commented on project_resource_calendar/tests/test_calendar_event.py
> +        calendar_event = self.task_1.info_calendar_event()
check that we have successfully an event clone

2019-04-17 14:30 UTC, rimbendhaou requested changes

2019-04-17 14:30 UTC, rimbendhaou commented on project_resource_calendar/tests/common.py
> +        self.Tasks = self.env['project.task']
Why you add this if you will not use it in the project_resource_calendar tests

2019-04-17 14:30 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +            error_msg = _('Clone task cannot be deleted')
Add the translation

2019-04-19 21:00 UTC, rimbendhaou commented
@wbeverly waiting for the warning message (fFr/Eng)

2019-04-24 19:06 UTC, rimbendhaou approved these changes

2019-04-24 19:06 UTC, rimbendhaou commented on project_event/tests/common.py
> +        self.room_4 = self.Rooms.create({
Is there any room 3? why directly room4?

2019-04-24 19:06 UTC, rimbendhaou commented on project_event/tests/common.py
> +        self.room_4 = self.Rooms.create({
If we already have a room and a partner and a responsible, we can use them

2019-04-24 19:06 UTC, merged