[ADD] Condition count and interval must be greater than 0
savoirfairelinux/project-addons pull request #428
Opened 2019-04-22 20:51 UTC by eilst

2019-04-24 19:57 UTC, rimbendhaou requested changes

2019-04-24 19:57 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                raise ValidationError(_('The interval must be greater than 0'))
add translation

2019-04-24 19:57 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +                    _('The number of repetitions must be greater than 0'))
add translation

2019-04-29 15:36 UTC, eilst commented on project_resource_calendar/models/calendar_event.py
> +                raise ValidationError(_('The interval must be greater than 0'))
done

2019-04-29 15:37 UTC, eilst commented on project_resource_calendar/models/calendar_event.py
> +                    _('The number of repetitions must be greater than 0'))
done

2019-04-29 16:11 UTC, closed without merging

2019-04-29 16:12 UTC, eilst commented
Detached HEAD problems, ner PR: https://github.com/savoirfairelinux/project-addons/pull/433