[FIX] Refactoring the status check for Task State in Project.task
savoirfairelinux/project-addons pull request #429
Opened 2019-04-23 17:14 UTC by jananjoy

2019-04-23 17:22 UTC, eilst commented
squash your merges in 1 commit

2019-04-24 20:03 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    def check_task_state(self, task_state_in):
You didnt use the self

2019-04-24 20:03 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        if task_state_in in \
simply return task_state_in in ...

2019-04-29 17:43 UTC, jananjoy commented on project_event/models/project_task.py
> +        if task_state_in in \
@rimbendhaou ok

2019-04-29 17:58 UTC, jananjoy commented on project_event/models/project_task.py
> +    def check_task_state(self, task_state_in):
@rimbendhaou  ok

2019-04-29 19:09 UTC, rimbendhaou approved these changes

2019-04-29 19:10 UTC, rimbendhaou requested changes
resolve conflicts

2019-05-01 20:50 UTC, rimbendhaou requested changes

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        if self.is_type_task() and  \
extra space (PEP8)

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        check_task_type_vals = {
you can simply use the self.task1 that is created in the common file

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        self.assertEqual(task.name, 'Sample Task for checking task type')
no need to check this

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        self.assertEqual(task.activity_task_type, 'task')
no need to check this

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        self.assertEqual(check_task_type, True)
simply : self.assertTrue(self.task1is_type_task())

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        check_task_state_vals = {
same comment: use the task created in common

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        self.assertEqual(task.name, 'Sample Task for checking task state')
No need to check this

2019-05-01 20:50 UTC, rimbendhaou commented on project_event/tests/test_project_event_task.py
> +        self.assertEqual(check_task_state, True)
simply check these 2 cases:
self.assertTrue(self.task1.check_task_state('draft'))
self.assertFalse(self.task1.check_task_state('......any state that is not in the test domain'))

2019-05-06 16:55 UTC, rimbendhaou approved these changes

2019-05-06 16:56 UTC, merged

2019-05-22 16:15 UTC, eilst reviewed
LGTM