[FIX] Sequence number for ' Room types  and Miscellaneous'
savoirfairelinux/project-addons pull request #436
Opened 2019-05-02 20:18 UTC by jananjoy

2019-05-06 14:52 UTC, rimbendhaou requested changes

2019-05-06 14:52 UTC, rimbendhaou commented on project_resource_calendar/views/miscellaneous_view.xml
> +    <record id="resource_calendar_miscellaneous_tree" model="ir.ui.view">
we already have a tree, just modify it

2019-05-06 14:52 UTC, rimbendhaou commented on project_resource_calendar/views/room_type_view.xml
> +    <record id="room_type_tree" model="ir.ui.view">
same comment (tree already exist)

2019-05-06 14:52 UTC, rimbendhaou commented on project_resource_calendar/models/room_type.py
> +    sequence = fields.Integer(
add order by sequence

2019-05-08 14:27 UTC, rimbendhaou approved these changes

2019-05-08 14:28 UTC, rimbendhaou reviewed
translation

2019-05-08 14:28 UTC, rimbendhaou requested changes
add translation for Sequence--> Séquence

2019-05-08 15:21 UTC, eilst commented on project_resource_calendar/models/miscellaneous.py
>  class Miscellaneous(models.Model):
@jananjoy I think we should remove this model, it's not used anywhere, right?

2019-05-08 15:44 UTC, eilst commented
LGTM

2019-05-08 15:44 UTC, eilst approved these changes

2019-05-08 15:46 UTC, rimbendhaou approved these changes

2019-05-08 15:46 UTC, merged