11 lmg fix message prompt
savoirfairelinux/project-addons pull request #473
Opened 2019-05-31 15:38 UTC by lgharib

11 lmg fix message prompt

2019-06-03 17:44 UTC, rimbendhaou requested changes

2019-06-03 17:44 UTC, rimbendhaou commented on project_event/models/project_task.py
> +    def is_hr_resource_double_booked(self, attendee, date_start, date_end):
For the method is_hr_resource_booked, i forget to check if it is not the same event_task_id, so when added we have to merge the 2 methods and keep only one

2019-06-03 17:44 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +            ('id', '!=', self.id),
we need to factor this redandant code, we can use a constatnt (OVERLAP_DOMAIN = [
            ('id', '!=', self.id),('start', '<', date_end),
            ('stop', '>', date_start),
            ('state', '!=', 'cancelled'),] and use it each time (we simply add the specific fields to check ( ('partner_ids', 'in', attendee.id))

2019-06-03 20:11 UTC, eilst commented on project_event/models/project_task.py
> +    def get_double_booked_resources(self, date_start=None, date_end=None):
hey, this methods are duplicated code. Just a comment, but you could reference the object and without creating it and make these verifications.

2019-06-05 18:10 UTC, rimbendhaou requested changes

2019-06-05 18:10 UTC, rimbendhaou commented on project_resource_calendar/models/calendar_event.py
> +        overlap_domain = [
overlap_domain should be after (if not date_end and not date_start:)

2019-06-05 19:58 UTC, rimbendhaou approved these changes

2019-06-05 19:59 UTC, merged