11 lg rights
savoirfairelinux/project-addons pull request #508
Opened 2019-07-17 19:12 UTC by eilst

2019-07-17 20:48 UTC, rimbendhaou commented on project_event/models/project_task.py
> +        self.env.ref('project.task.merge.wizard.project_task_actions_act_window_merge_tasks').unlink()
check this link : https://www.odoo.com/fr_FR/forum/aide-1/question/use-domain-in-act-window-based-on-uid-132683

2019-07-18 15:38 UTC, rimbendhaou requested changes

2019-07-18 15:38 UTC, rimbendhaou commented on project_event/static/src/js/disable_archive_action.js
> +                    session.user_has_group('project_event.group_project_event_manage').then(function(has_group) {
```suggestion
                    session.user_has_group('project_event.group_project_event_manager').then(function(has_group) {
```

2019-07-18 16:52 UTC, lgharib approved these changes

2019-07-18 16:58 UTC, rimbendhaou approved these changes

2019-07-18 16:58 UTC, merged