[DEV] Add new fields in the task tree
savoirfairelinux/project-addons pull request #85
Opened 2018-10-01 21:20 UTC by jananjoy

Add new fields in the task tree and update the language translation for the project event module

2018-10-01 21:24 UTC, eilst commented on project_event/i18n/fr.po
> +msgstr "Assistant Activités"
Wizard d'activités

2018-10-01 22:41 UTC, rimbendhaou requested changes

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant Activités"
@jananjoy Wizard d'activités

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Titre des activités"
@jananjoy Titre d'activité

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant Activités"
@jananjoy Wizard d'activités

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Affichage du calendrier"
@jananjoy Vue Calendrier

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Clair"
@jananjoy Supprimer tout

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Crée par"
@jananjoy Créé par

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Créer sur"
@jananjoy Créé le

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "La description"
@jananjoy Description

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Afficher un nom"
@jananjoy Nom affiché

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Terminé"
@jananjoy Réalisé

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Modèle d'activités"
@jananjoy Modèle d'activité

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Catégories d'activités"
@jananjoy Catégories d'activité

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Des employés"
@jananjoy Employés

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr ""
@jananjoy Titre d'événement

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Event  Wizard"
@jananjoy Wizard d'événement

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +"L'événement sera créé à partir du modèle dans le brouillon afin que vous puissiez examiner\n"
@jananjoy L'événement sera créé à l'état brouillon à partir du modèle afin que vous puissiez l'examiner avant la validation.

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr ""
@jananjoy Dernière mise à jour le

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Remarques"
@jananjoy Notes

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Événement de projet"
 @jananjoy Événement

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Recherche de tâche de projet"
@jananjoy Recherche de tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Read"
@jananjoy Lu

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Demande"
@jananjoy Demander

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr ""
@jananjoy Revenir à brouillon

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Chercher"
@jananjoy Recherche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Catégories de tâches"
@jananjoy Catégories de tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Catégorie de tâches"
@jananjoy Catégorie de tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Tâche Client"
@jananjoy Client de la tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Tâche responsable"
@jananjoy Responsable de la tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Etat de tâche"
@jananjoy État de tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant de tâche"
@jananjoy Wizard de tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Ordre de Tâche"
@jananjoy Ordre de tâche

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Les tâches"
@jananjoy Tâches

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant Tâches"
@jananjoy Wizard de tâches

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Evénement de modèle"
@jananjoy Modèle d'événement

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant Création d'un événement à partir d'un modèle"
@jananjoy Wizard de création d'activité à partir d'un modèle

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant de création d'assistant à partir d'un modèle"
@jananjoy Wizard de création d'un événement à partir d'un modèle

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/i18n/fr.po
> +msgstr "Assistant Création d'une tâche à partir d'un modèle"
@jananjoy Wizard de création d'une tâche à partir d'un modèle

2018-10-01 22:41 UTC, rimbendhaou commented on project_event/views/project_task_view.xml
> +                <field name="room_id"/>
@jananjoy string="Room"

2018-10-02 15:18 UTC, jananjoy commented
Complete language translation for "French" language  is integrated into this branch .

2018-10-02 15:40 UTC, rimbendhaou approved these changes
looks good

2018-10-02 15:40 UTC, merged