[ADD] View activities and tasks by start order
savoirfairelinux/project-addons pull request #89
Opened 2018-10-02 19:20 UTC by jananjoy

View Activities and Tasks in Start Order

2018-10-02 20:11 UTC, eilst approved these changes

2018-10-04 20:24 UTC, eilst approved these changes

2018-10-05 22:42 UTC, rimbendhaou requested changes
@jananjoy add sort by date start for task tree also

2018-10-09 16:19 UTC, jananjoy commented
@rimbendhaou : Changes are made accordingly

2018-10-09 19:50 UTC, rimbendhaou approved these changes
looks ok

2018-10-09 19:50 UTC, merged